# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 20:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Administrador', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=30, null=True)),
                ('Owner', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=30, null=True)),
                ('Negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='negocio_perfil', to='sar.Negocio', verbose_name='negocio_perfil')),
                ('Usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_usario', to=settings.AUTH_USER_MODEL, verbose_name='perfil_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('Precio', models.FloatField(blank=True, default=0, null=True)),
                ('Campo_1', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('Valor_1', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
        ),
    ]
