# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='negocio_producto', to='sar.Negocio', verbose_name='negocio_producto'),
        ),
    ]
