# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 20:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sar', '0002_producto_negocio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tiempo', models.DateTimeField(auto_now_add=True)),
                ('Valor_1', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('Valor_2', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='Valor_1',
            new_name='Campo_2',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='Usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_perfil', to=settings.AUTH_USER_MODEL, verbose_name='usuario_prefil'),
        ),
        migrations.AddField(
            model_name='venta',
            name='Perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_venta', to='sar.Perfil', verbose_name='perfil_venta'),
        ),
        migrations.AddField(
            model_name='venta',
            name='Producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_venta', to='sar.Producto', verbose_name='producto_venta'),
        ),
    ]
