# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sar', '0003_auto_20171112_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Campo_2',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='Valor_2',
        ),
        migrations.AddField(
            model_name='producto',
            name='Cantidad',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='Cantidad',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
