# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sar', '0004_auto_20171113_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anyo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anyo', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dia', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mes', models.IntegerField(blank=True, default=0, null=True)),
                ('Nombre', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('Anyo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_anyo', to='sar.Anyo', verbose_name='mes_anyo')),
            ],
        ),
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dia',
            name='Mes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dia_mes', to='sar.Mes', verbose_name='dia_mes'),
        ),
    ]
