# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sar', '0005_auto_20171114_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='Dia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dia_venta', to='sar.Dia', verbose_name='dia_venta'),
        ),
        migrations.AddField(
            model_name='venta',
            name='Semana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semana_venta', to='sar.Semana', verbose_name='semana_venta'),
        ),
    ]
