# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sar', '0006_auto_20171114_0429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semana',
            old_name='Nombre',
            new_name='Numero',
        ),
    ]
