# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sar', '0007_auto_20171113_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.FloatField(blank=True, default=0, null=True)),
                ('Total', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dia',
            name='Semana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semana_dia', to='sar.Semana', verbose_name='semana_dia'),
        ),
        migrations.AddField(
            model_name='tag',
            name='Dia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dia_tag', to='sar.Dia', verbose_name='dia_tag'),
        ),
    ]
