# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sar', '0010_auto_20171118_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semana',
            name='FMes',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='semana',
            name='IMes',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
