# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sar', '0011_auto_20171118_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='semana',
            name='Anyo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semana_anyo', to='sar.Anyo', verbose_name='semana_anyo'),
        ),
    ]
